#if 0
//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.960.8229
//
//   fxc /nologo /Qstrip_reflect /T ps_2_0 /E PS /Fh
//    Z:/projects/apitrace/tests/apps/d3dcommon/tri_ps_2_0.h
//    Z:/projects/apitrace/tests/apps/d3dcommon/tri.fx
//
    ps_2_0
    dcl v0
    mov oC0, v0

// approximately 1 instruction slot used
#endif

const BYTE g_ps20_PS[] =
{
      0,   2, 255, 255, 254, 255, 
     22,   0,  67,  84,  65,  66, 
     28,   0,   0,   0,  35,   0, 
      0,   0,   0,   2, 255, 255, 
      0,   0,   0,   0,   0,   0, 
      0,   0,   0,   1,   0,   0, 
     28,   0,   0,   0, 112, 115, 
     95,  50,  95,  48,   0,  77, 
    105,  99, 114, 111, 115, 111, 
    102, 116,  32,  40,  82,  41, 
     32,  72,  76,  83,  76,  32, 
     83, 104,  97, 100, 101, 114, 
     32,  67, 111, 109, 112, 105, 
    108, 101, 114,  32,  57,  46, 
     51,  48,  46,  57,  54,  48, 
     46,  56,  50,  50,  57,   0, 
     31,   0,   0,   2,   0,   0, 
      0, 128,   0,   0,  15, 144, 
      1,   0,   0,   2,   0,   8, 
     15, 128,   0,   0, 228, 144, 
    255, 255,   0,   0
};
