#if 0
//
// Generated by Microsoft (R) D3DX9 Shader Compiler 5.04.00.2904
//
//   fxc /nologo /T ps_1_1 /E PS /Fh tri_ps_1_1.h tri.fx
//
    ps_1_1
    mov r0, v0

// approximately 1 instruction slot used
#endif

const DWORD g_ps11_PS[] =
{
    0xffff0101, 0x0016fffe, 0x42415443, 0x0000001c, 0x00000023, 0xffff0101, 
    0x00000000, 0x00000000, 0x00000100, 0x0000001c, 0x315f7370, 0x4d00315f, 
    0x6f726369, 0x74666f73, 0x29522820, 0x44334420, 0x53203958, 0x65646168, 
    0x6f432072, 0x6c69706d, 0x35207265, 0x2e34302e, 0x322e3030, 0x00343039, 
    0x00000001, 0x800f0000, 0x90e40000, 0x0000ffff
};
