#if 0
//
// Generated by Microsoft (R) D3DX9 Shader Compiler 5.04.00.2904
//
//   fxc /nologo /T vs_1_1 /E VS /Fh tri_vs_1_1.h tri.fx
//
    vs_1_1
    dcl_position v0
    dcl_color v1
    mov oPos, v0
    mov oD0, v1

// approximately 2 instruction slots used
#endif

const DWORD g_vs11_VS[] =
{
    // D3DVS_VERSION(1, 1)
    0xfffe0101, 

#if 0
    // D3DSIO_COMMENT
    0x0016fffe,
    0x42415443, 0x0000001c, 0x00000023, 0xfffe0101, 0x00000000, 0x00000000,
    0x00000100, 0x0000001c, 0x315f7376, 0x4d00315f, 0x6f726369, 0x74666f73,
    0x29522820, 0x44334420, 0x53203958, 0x65646168, 0x6f432072, 0x6c69706d,
    0x35207265, 0x2e34302e, 0x322e3030, 0x00343039, 
#endif

    // XXX: IDirect3DDevice8::CreateVertexShader fails if these are present
#if 0
    // dcl_position v0
    0x0000001f, 0x80000000, 0x900f0000, 

    // dcl_color v1
    0x0000001f, 0x8000000a, 0x900f0001, 
#endif

    // mov oPos, v0
    0x00000001, 0xc00f0000, 0x90e40000, 

    // mov oD0, v1
    0x00000001, 0xd00f0000, 0x90e40001, 

    // D3DVS_END()
    0x0000ffff
};
