FROM ubuntu:16.04
MAINTAINER "Jose Fonseca" <jfonseca@vmware.com>
ENV container docker

RUN apt-get update && apt-get install -y build-essential zlib1g-dev libdwarf-dev libx11-dev libgl-dev libwaffle-dev python2.7 ninja-build cmake

CMD ["/bin/bash"]
