Import('env')

env.SharedLibrary(
    target = 'd3d9.dll',
    source = [
        'd3d9.def',
        'dllmain.cpp',
        'idirect3d9.cpp',
        'idirect3d_device9.cpp',
        'idirect3d_swapchain9.cpp',
    ]
)
