Import('*')

zenv = env.Clone()

zlib = zenv.StaticLibrary(
	target = 'zlib',
	source = [
        'adler32.c',
        'compress.c',
        'crc32.c',
        'gzio.c',
        'uncompr.c',
        'deflate.c',
        'trees.c',
        'zutil.c',
        'inflate.c',
        'infback.c',
        'inftrees.c',
        'inffast.c',
	],
)

env.Append(CPPPATH = ['#zlib'])
env.Prepend(LIBS = [zlib])

