dump --verbose zlib-no-eof.trace
0 glXQueryExtension(dpy = 0x1da4360, errorb = NULL, event = NULL) = True
1 glXChooseFBConfig(dpy = 0x1da4360, screen = 0, attribList = {GLX_RED_SIZE, GLX_USE_GL, GLX_GREEN_SIZE, GLX_USE_GL, GLX_BLUE_SIZE, GLX_USE_GL, GLX_ALPHA_SIZE, GLX_USE_GL, GLX_DOUBLEBUFFER, GLX_USE_GL, 0}, nitems = &42) = {0x1e36000, 0x1e36700, 0x1e36e00, 0x1e37500, 0x1e37c00, 0x1e38300, 0x1e38a00, 0x1e39100, 0x1e39800, 0x1e39f00, 0x1e35c80, 0x1e36380, 0x1e36a80, 0x1e37180, 0x1e37880, 0x1e37f80, 0x1e38680, 0x1e38d80, 0x1e39480, 0x1e39b80, 0x1e35e40, 0x1e36540, 0x1e36c40, 0x1e37340, 0x1e37a40, 0x1e38140, 0x1e38840, 0x1e38f40, 0x1e39640, 0x1e39d40, 0x1e35ac0, 0x1e361c0, 0x1e368c0, 0x1e36fc0, 0x1e376c0, 0x1e37dc0, 0x1e384c0, 0x1e38bc0, 0x1e392c0, 0x1e399c0, 0x1e3a1a0, 0x1e3a280}
2 glXGetVisualFromFBConfig(dpy = 0x1da4360, config = 0x1e36000) = &{visual = 0x1daf630, visualid = 41, screen = 0, depth = 24, c_class = 4, red_mask = 16711680, green_mask = 65280, blue_mask = 255, colormap_size = 256, bits_per_rgb = 8}
3 glXCreateNewContext(dpy = 0x1da4360, config = 0x1e36000, renderType = GLX_RGBA_TYPE, shareList = NULL, direct = True) = 0x1e1cad0
4 glXIsDirect(dpy = 0x1da4360, ctx = 0x1e1cad0) = True
5 glXMakeContextCurrent(dpy = 0x1da4360, draw = 69206018, read = 69206018, ctx = 0x1e1cad0) = True
6 glXMakeContextCurrent(dpy = 0x1da4360, draw = 69206018, read = 69206018, ctx = 0x1e1cad0) = True
7 glGetString(name = GL_RENDERER) = "ATI Mobility Radeon HD 3650"
8 glGetString(name = GL_VERSION) = "3.3.10666 Compatibility Profile Context"
9 glGetString(name = GL_VENDOR) = "ATI Technologies Inc."
10 glClearColor(red = 0.3, green = 0.1, blue = 0.3, alpha = 0)
11 glXMakeContextCurrent(dpy = 0x1da4360, draw = 69206018, read = 69206018, ctx = 0x1e1cad0) = True
12 glViewport(x = 0, y = 0, width = 250, height = 250)
13 glMatrixMode(mode = GL_PROJECTION)
14 glLoadIdentity()
15 glOrtho(left = -1, right = 1, bottom = -1, top = 1, zNear = -0.5, zFar = 1000)
16 glMatrixMode(mode = GL_MODELVIEW)
17 glXMakeContextCurrent(dpy = 0x1da4360, draw = 69206018, read = 69206018, ctx = 0x1e1cad0) = True
18 glXMakeContextCurrent(dpy = 0x1da4360, draw = 69206018, read = 69206018, ctx = 0x1e1cad0) = True
19 glClear(mask = GL_COLOR_BUFFER_BIT)
20 glBegin(mode = GL_TRIANGLES)
21 glColor3f(red = 0.8, green = 0, blue = 0)
22 glVertex3f(x = -0.9, y = -0.9, z = -30)
23 glColor3f(red = 0, green = 0.9, blue = 0)
24 glVertex3f(x = 0.9, y = -0.9, z = -30)
25 glColor3f(red = 0, green = 0, blue = 0.7)
26 glVertex3f(x = 0, y = 0.9, z = -30)
27 glEnd()
28 glFlush()
29 glFlush()
30 glXSwapBuffers(dpy = 0x1da4360, drawable = 69206018)

31 glXMakeContextCurrent(dpy = 0x1da4360, draw = 69206018, read = 69206018, ctx = 0x1e1cad0) = True
